### ISSUE TITLE
Incorrect namespace in readme

### ISSUE THREAD

**Issue by Max-AR** [mortola/behat-seo-contexts#17]
Hey mate, 

Using this lib and following the instructions in the readme shows;

`MarcOrtola\BehatSEOContexts\Context\` 

as the namespace. Looks like you've declared;

`MOrtola\BehatSEOContexts\Context\` 

instead.

Thanks!

**Comment by marcortola** [comment]
``MOrtola`` was the namespace used in 1.x and the 2.x versions of the library. Now we are using the ``MarcOrtola`` namespace (active in the master branch, but not yet release), so I guess you are reading the master Readme, not the release version one. Nice catch anyway, I'm going to release the 3.0.0 version.
