### ISSUE TITLE
Remove assertValidSitemap into dedicated step

### ISSUE THREAD

**Issue by normanlolx** [mortola/behat-seo-contexts#2]
In the very first sitemap step `public function theSitemap` which is needed for all subsequent steps the sitemap gets validated rather strictly against multiple schemas. Which is a real cool thing, but let's better make that a dedicated step.

Because the validation simply is too strict, I think. Assuming a sample sitemap without the initial `<?xml>` tag for example, this will simply fail the strict validation. But still it may be a valid sitemap, eaten by Google without any problem, and which URLs still can be checked afterwards in the `public function theSitemapUrlsAreAlive` step without any problem.

**Comment by marcortola** [comment]
That's a good point and it totally makes sense.

The isolation of the sitemap loading step definition would result in four new steps:

- Given the sitemap :url
- Then the sitemap should be valid
- Then the sitemap should be a valid index sitemap
- Then the sitemap should be a valid multilanguage sitemap

What do you think? If it's consistent with your approach, I can implement it during the next week.

**Comment by normanlolx** [comment]
That sounds absolutely perfect! Could the validation steps all be merged into one?

    "Then the sitemap should be a valid (index|multisite|) sitemap"

**Comment by normanlolx** [comment]
Refs https://www.drupal.org/project/simple_sitemap/issues/3019593

**Comment by marcortola** [comment]
92b1c336607a775e7247e6660cccf055f4895d1d fixes it. I forgot to reference this issue in the commit message.

Now you have two new steps:
- Given the sitemap :sitemapUrl
- Then /^the sitemap should be a valid (index |multilanguage |)sitemap$/

I have released the v0.3 version too.

**Comment by normanlolx** [comment]
Thanks a lot Marc! I really appreciate your efforts and will spread the word about this whole useful extension.
