### ISSUE TITLE
Add some tests

### ISSUE THREAD

**Issue by marcortola** [mortola/behat-seo-contexts#3]

**Comment by andreitic** [comment]
Hi, good idea for this project! 
I have some ideas that I could contribute with, but I have a question:
Any reason to not uppercase the step definitions ? It would be more consistent with the doc and the other extensions projects.
Thanks!

**Comment by marcortola** [comment]
Hi, Andrei.
Where have you seen step definitions written using uppercase letters?
Thank you for your comment!

**Comment by andreitic** [comment]
Sorry I wasn't clear enough, I meant the first letter, like in Behat doc for example:
`Given I am in a directory "test"`
`And I have a file named "foo"`

**Comment by marcortola** [comment]
I understand it better now, thanks for clarifying. In which classes (in this repo) have you seen not capitalized step definitions?

**Comment by andreitic** [comment]
They are good, its my fault broke something while testing :sweat_smile:

**Comment by marcortola** [comment]
No problem! I'm creating the tests this week.
